apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ngrok.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "ngrok.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "ngrok.fullname" . }}
    spec:
      containers:
      - name: {{ template "ngrok.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["ngrok"]
        args: ["http", "nginx-service"]
        ports:
        - containerPort: {{ .Values.ports.container }}
        {{- if .Values.env }}
        env:
        {{- range $key, $val := .Values.env }}
        - name: {{ $key }}
          value: "{{ $val }}"
        {{- end}}
      {{- end }}
