apiVersion: v1
kind: Service
metadata:
  name: {{ template "ngrok.name" . }}
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.ports.service }}
      targetPort: {{ .Values.ports.container }}
      protocol: TCP
  selector:
    app: {{ template "ngrok.name" . }}
