{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ngrok.fullname" . }}
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.ports.service }}
      targetPort: {{ .Values.ports.container }}
      protocol: TCP
  selector:
    app: {{ template "ngrok.fullname" . }}
{{- end }}
