apiVersion: apps/v1
kind: Deployment
metadata:
  name: { template "nginx.name" . }}
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: {{ template "nginx.name" . }}
        image: {{ .Values.image.repository }}
        tag: {{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.ports.container }}
        env:
          {{- range $key, $val := .Values.env }}
          - name: {{ $key }}
            value: {{ $val }}
          {{- end}}
