apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nginx.fullname" . }}
spec:
  selector:
    matchLabels:
      run: {{ template "nginx.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        run: {{ template "nginx.fullname" . }}
    spec:
      containers:
      - name: {{ template "nginx.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.ports.container }}
        {{- if .Values.env }}
        env:
          {{- range $key, $val := .Values.env }}
          - name: {{ $key }}
            value: {{ $val }}
          {{- end}}
        {{- end }}
