apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    run: {{ template "nginx.name" . }}
spec:
  ports:
  - port: {{ .Values.ports.service }}
    protocol: TCP
  selector:
    run: {{ template "nginx.name" . }}
